name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '*deploy*')"
    steps:
      - name: Check free space before maximize
        run: |
          echo "Free space before maximize:"
          df -h
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 8192
          remove-dotnet: 'true'
      - name: Check free space after maximize
        run: |
          echo "Free space after maximize:"
          df -h
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: utils/container/Dockerfile
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/spcl/pspin:latest
